[profile.default]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
src = "src"
test = "test"
libs = ["lib"]


remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/",
]

[lint]
exclude_lints = [
    "mixed-case-function",
    "mixed-case-variable",
    "screaming-snake-case-immutable",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
